
package ru.atconsulting.bigdata.services.glassfish.sis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SubscriberHierarchy", targetNamespace = "urn:gf-subscriber-info-service:wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SubscriberHierarchy {


    /**
     * 
     * @param request
     * @return
     *     returns ru.atconsulting.bigdata.client.glassfish.generated.ResponseHierarchy
     * @throws ServiceException
     */
    @WebMethod(operationName = "SubscriberHierarchy")
    @WebResult(name = "responseHierarchy", targetNamespace = "urn:gf-subscriber-info-service:xsd", partName = "response")
    public ResponseHierarchy subscriberHierarchy(
            @WebParam(name = "requestHierarchy", targetNamespace = "urn:gf-subscriber-info-service:xsd", partName = "request")
            RequestHierarchy request)
        throws ServiceException
    ;

}
