
package ru.atconsulting.bigdata.services.glassfish.sis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SubscribeInfo", targetNamespace = "urn:gf-subscriber-info-service:wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SubscribeInfo {


    /**
     * 
     * @param request
     * @return
     *     returns ru.atconsulting.bigdata.client.glassfish.generated.Response
     * @throws ServiceException
     */
    @WebMethod(operationName = "SubscribeInfo")
    @WebResult(name = "response", targetNamespace = "urn:gf-subscriber-info-service:xsd", partName = "response")
    public Response subscribeInfo(
            @WebParam(name = "request", targetNamespace = "urn:gf-subscriber-info-service:xsd", partName = "request")
            Request request)
        throws ServiceException
    ;

    /**
     * 
     * @param request
     * @return
     *     returns ru.atconsulting.bigdata.client.glassfish.generated.ResponseBan
     * @throws ServiceException
     */
    @WebMethod(operationName = "SubscribeBanInfo")
    @WebResult(name = "responseBan", targetNamespace = "urn:gf-subscriber-info-service:xsd", partName = "response")
    public ResponseBan subscribeBanInfo(
            @WebParam(name = "requestBan", targetNamespace = "urn:gf-subscriber-info-service:xsd", partName = "request")
            RequestBan request)
        throws ServiceException
    ;

}
