
package ru.atconsulting.bigdata.services.glassfish.trouble;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "getTTInfoByCoordinateFault", targetNamespace = "urn:gf-case-to-trouble:service:types")
public class GetTTInfoByCoordinateFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GetTTInfoByCoordinateFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GetTTInfoByCoordinateFault_Exception(String message, GetTTInfoByCoordinateFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GetTTInfoByCoordinateFault_Exception(String message, GetTTInfoByCoordinateFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.atconsulting.bigdata.client.glassfish.trouble.GetTTInfoByCoordinateFault
     */
    public GetTTInfoByCoordinateFault getFaultInfo() {
        return faultInfo;
    }

}
